# Generated by Django 4.2.8 on 2026-01-04 03:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='User phone number', max_length=20, null=True)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('journalist', 'Journalist'), ('ngo', 'NGO'), ('admin', 'Admin')], default='citizen', help_text='User role in the system', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='User bio/description', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, help_text='User location/city', max_length=100, null=True)),
                ('organization', models.CharField(blank=True, help_text='User organization (for journalists/NGOs)', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Phone number verification status')),
                ('is_identity_verified', models.BooleanField(default=False, help_text='Identity verification (for journalists/NGOs)')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Two-factor authentication enabled')),
                ('two_factor_method', models.CharField(blank=True, choices=[('email', 'Email OTP'), ('sms', 'SMS OTP')], default='email', max_length=20, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_submission_date', models.DateTimeField(blank=True, null=True)),
                ('submission_count', models.IntegerField(default=0, help_text='Total submissions by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('submission', 'Submission'), ('profile_update', 'Profile Update'), ('role_change', 'Role Change'), ('admin_action', 'Admin Action')], help_text='Type of activity', max_length=50)),
                ('description', models.TextField(help_text='Activity description')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which activity was performed')),
                ('user_agent', models.TextField(blank=True, help_text='User agent of request', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_133bc2_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_cdda35_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('verification_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('2fa', 'Two-Factor Auth'), ('password_reset', 'Password Reset')], help_text='Type of verification', max_length=20)),
                ('email_or_phone', models.CharField(help_text='Email or phone to verify', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('user', models.ForeignKey(help_text='User requesting OTP', on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'verification_type'], name='otp_verific_user_id_72684b_idx'), models.Index(fields=['email_or_phone'], name='otp_verific_email_o_ba20d9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='auth_user_role_f90fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='auth_user_is_veri_c40f2e_idx'),
        ),
    ]
